# Generated by Django 6.0.6 on 2026-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('class_name', models.CharField(default='Full Stack Developer', max_length=100)),
                ('server', models.CharField(default='Kerala, India', max_length=100)),
                ('bio', models.JSONField(default=list, help_text='Array of paragraphs')),
                ('years_experience', models.IntegerField(default=3)),
                ('projects_built', models.IntegerField(default=12)),
                ('technologies_known', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_or_school', models.CharField(max_length=150)),
                ('role_or_degree', models.CharField(max_length=150)),
                ('start_date', models.CharField(help_text='e.g. 2021-08 or Aug 2021', max_length=30)),
                ('end_date', models.CharField(blank=True, help_text='Leave blank if current', max_length=30, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Newline separated bullet points')),
                ('type', models.CharField(choices=[('work', 'Work'), ('education', 'Education')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_stack', models.JSONField(default=list, help_text='Array of technologies')),
                ('github_url', models.URLField()),
                ('live_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools & Weapons')], max_length=20)),
                ('proficiency', models.IntegerField(help_text='1 to 100')),
                ('is_hotbar', models.BooleanField(default=False, help_text='Highlight in top skills')),
            ],
        ),
    ]
