# Generated by Django 6.0.6 on 2026-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='instagram',
            field=models.URLField(blank=True, default='https://instagram.com/abhishek__muralidharan'),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.URLField(blank=True, default='https://x.com/abhishekm_nair'),
        ),
    ]
